/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AuroraBackground: typeof import('./src/components/AuroraBackground.vue')['default']
    AuroraBackgroundDemo: typeof import('./src/components/AuroraBackgroundDemo.vue')['default']
    CalendarModule: typeof import('./src/components/modules/CalendarModule.vue')['default']
    ChatModule: typeof import('./src/components/modules/ChatModule.vue')['default']
    DailyLearning: typeof import('./src/components/DailyLearning.vue')['default']
    Dashboard: typeof import('./src/components/Dashboard.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    NotesModule: typeof import('./src/components/modules/NotesModule.vue')['default']
    PersonalSettings: typeof import('./src/components/PersonalSettings.vue')['default']
    PomodoroModule: typeof import('./src/components/PomodoroModule.vue')['default']
    ProjectFramework: typeof import('./src/components/ProjectFramework.vue')['default']
    ProjectManagement: typeof import('./src/components/ProjectManagement.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./src/components/Settings.vue')['default']
    TaskManagement: typeof import('./src/components/TaskManagement.vue')['default']
    TodosModule: typeof import('./src/components/modules/TodosModule.vue')['default']
    Tutorial: typeof import('./src/components/Tutorial.vue')['default']
    WorkLog: typeof import('./src/components/WorkLog.vue')['default']
  }
}
